export enum Error {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  COURSE_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_NOT_FOUND",
  COURSE_ALREADY_EXISTS = "USER_NOT_FOUND",
  RUNTIME_ERROR = "RUNTIME_ERROR",
  DATABASE_ERROR = "DATABASE_ERROR",
}
